### PR TITLE
List only active packages

### PR DESCRIPTION
**Pull request by icemac**
Aka omit the archived ones.

Modeled using https://developer.github.com/v3/repos/#list-organization-repositories
not tested locally.

### CODE REVIEW

**Review by mgedmin — CHANGES_REQUESTED** [review]
`get_github_list()` is generic, and if we want to add filtering, let's do it properly: extra keyword arguments that get transplanted into the URL string.

Note that there are two `get_json_and_headers()` calls in the function body, and you updated only one of them.  (Ideally I'd extract the next page URL from the Link: rel="next" header, instead of manually incrementing page numbers.  Then it will be enough to update one URL construction with all the filter arguments, instead of having to keep both in sync.)

I'm a bit surprised that filtering on `type=sources` eliminates archived repositories.  In fact I won't believe it until I see it ;-).  Nevertheless, filtering by type=sources might be a good idea in any case.

**Comment by mgedmin** [comment]
I'm pretty sure all you need to do is add an `if repo['archived']: continue` check in the for loop inside `list_zope_packages_from_github()`.

**Comment by mgedmin** [comment]
I've implemented this.  Thank you for figuring out which script to modify, because I'd forgotten everything about how this pile of garbage duct-taped together worked!

**Comment by icemac** [comment]
Thank you very much!

**Pull request closed without merging**
